### ISSUE TITLE
需要调研新浪微博官方的好友邀请组件

### ISSUE THREAD

**Issue by pimgeek** [mindpin/TouchIdea#11]
经宋亮的简单调查，新浪微博官方提供了一个好友邀请组件。利用这个组件，可以实现的大概效果如下：

![](http://img.teamkn.com/i/dhytaPv3.png)

目前利用 pinidea.4ye.me 的组件也可以实现类似的功能，但还处在迭代初期。

![](http://img.teamkn.com/i/MRi64qzt.png)

现在需要调研新浪微博官方的好友邀请组件，调研的主要目的是：评估新浪微博的官方提供的这一组件，是否可以替代目前 #7 以及部分相关组件。

微博官方好友邀请组件参考链接如下：

组件地址 - http://open.weibo.com/widget/js#publisher
官方文档 - http://open.weibo.com/wiki/index.php/Weibo-JS_V2#.E5.BE.AE.E5.8D.9A.E5.A5.BD.E5.8F.8B.E9.80.89.E6.8B.A9.E5.99.A8

**Comment by pimgeek** [comment]
### 调研结果概要：

@destinyd  提到：

“看了下支持回调，能获取名称以及ID，下面回答组件调研说明中所提的问题：
1. 【是否易用？】需要一定的diy，但是相对来说较易用
2. 【替换后的影响？】替换的话，主要是花时间去修改，还有就是对于原有已经选择的场景，暂时不知道能否处理
3. 【有何局限？】对于原有已经选择的场景，暂时不知道能否处理。还有就是，对于隐藏了的好友，用户可能不知道可以通过搜索找到”

### 后续工作

根据调研结果，@pimgeek 决定改用新浪微博官方好友邀请组件实现 pinidea 的好友邀请 feature。

**Comment by ben7th** [comment]
讨论在：
https://github.com/mindpin/TouchIdea/issues/15
中继续
