### ISSUE TITLE
2015-03-06 对 pinidea.4ye.me 产品简单试水的思路和执行结果

### ISSUE THREAD

**Issue by pimgeek** [mindpin/TouchIdea#12]
从 2015-03-06 到 2015-03-09 期间。@pimgeek 基于 pinidea.4ye.me v7 版进行了一次微博/微信试水推广。
## 大体操作步骤

整个试水思路分三个步骤：内容准备，渠道发布，分析反思
### 内容准备

1 确定投票主题：选择一个 @pimgeek 持续关注超过 90 天的话题领域，如扇贝单词App。
2 确定投票要点和选项：从扇贝单词App的使用过程中寻找亮点，分若干个大类列举出来。
3 获得用于发布的永久链接
### 渠道发布

1 微信发布：通过个人的微信朋友圈发放一次，再通过永久链接转发给一部分熟人群组和认知科学爱好者的微信讨论群组发放一次。
2 微博发布：通过个人的微博时间线发放一次，再通过粉丝数超过 8w 的科普作家微博账号发放一次。
3 扇贝官方论坛发布：在产品问答版面发放一次，在活跃度排名TOP5的版面中择一到两个发放一次。
4 扇贝非官方 QQ 群发布：在活跃度排名TOP5的扇贝单词相关群组中择一到两个发放一次。
### 分析反思

1 利用 tongji.cnzz.com 进行访客来源等统计分析（事先为 pinidea.4ye.me 的主要页面嵌入了统计代码）
2 根据统计结果做出靠谱的结论。
## 操作后得出的最终结论

投票发布后的第 3 天进行统计分析，得到结论是：pinidea.4ye.me 参与投票人数少于预期
【投票详情页展示近100次，实际通过微博登录的团队外用户只有 2 位，这 2 位都完成了投票】

经过数据筛查，@pimgeek 推断是【投票的主题内容或者界面没能吸引预定的目标用户登录并投票】，这才导致数十位来访者只是浏览过投票主题，而没有真正使用微博登录（数据分析之前，推测是微博登录过，但未完成投票）。

**Comment by ben7th** [comment]
经过简单策划的投票主题 - http://pinidea.4ye.me/VUpr6n
寻求的微博推广账号 - http://weibo.com/1216002517/C7hWNCvur
相关推广文案 - https://workflowy.com/s/t1RTLhJxDc
在扇贝网小组中的试水推广文（之一） - http://shanbay.com/team/thread/6/408031/
已经参与的 QQ 群组（之一）：青梅煮酒论学霸-扇贝（68332971）
实际的试水推广效果统计图 - http://img.teamkn.com/i/FQwutk3W.png
多人议事场景概要：自发的聚餐/旅游活动出行前的讨论  - http://mindmap.4ye.me/LPWn9cFi

**Comment by ben7th** [comment]
0.3 版运营推广计划已部分涵盖这些内容
