### ISSUE TITLE
infocard 案例收集任务

### ISSUE THREAD

**Issue by ben7th** [mindpin/TouchIdea#19]
此任务来自：
https://github.com/mindpin/TouchIdea/issues/18

由于 pinidea 0.2 所涉及的场景需要采集/解析商品信息，并且生成 infocard，因此需要针对不同的网站进行案例收集。
#### infocard 案例收集：

收集的内容：针对每个商品网站，简单研究其商品页面。

收集的范围：

![](http://img.teamkn.com/i/HoQiPWLw.png)

像豆瓣东西里列出的这些网站，都可以作为案例涉及的范围。
**而由于我们要做的场景并非局限于实体消费品领域，因此可以把案例选取得更广一些。**
一些书籍信息网站也可以作为案例。
一些软件产品推荐网站或者开源项目推荐网站都可以作为案例。
点评类网站也可以作为案例。

在宋亮完成 pinidea 0.2 的 UI 实现之前，多多愈善地收集案例，并按以下方式记录。

```
网站名称：
网站首页地址：
示例商品页地址：
能够采集的商品关键元信息，以及如何采集的示意图，包括：
   - 图片
   - 商品名称
   - 商品描述
   - 定价
   - 地理位置

   以上五个属性基本上领域性不太强，无论是实体商品，餐饮服务，软件产品，基本上都可能具备这五个属性。如果页面上能找到这些属性，通过示意图给出位置。如果不能找到就忽略。
```

案例范例：http://markdown.4ye.me/a70Rlgho

**Comment by ben7th** [comment]
二楼和以后的楼层用于记录已收集的案例，使用 markdown.4ye.me 记录。为方便浏览，每个记录作为一个链接。格式如下：

淘宝网：http://markdown.4ye.me/a70Rlgho

**Comment by chilliza** [comment]
天猫：http://markdown.4ye.me/z1ei2y6c
京东：http://markdown.4ye.me/klxVBaYz
亚马逊（中国）：http://markdown.4ye.me/dwpFM336
凡客：http://markdown.4ye.me/KAGHbgz2
当当：http://markdown.4ye.me/Sh5kEhfY
1号店：http://markdown.4ye.me/unEbYpEy
AliceInMod：http://markdown.4ye.me/k2CAyyJI
易迅：http://markdown.4ye.me/GTH2qw0w
宜家：http://markdown.4ye.me/aPckCMRZ
趣玩：http://markdown.4ye.me/DIT6WpP3
好乐买：http://markdown.4ye.me/VxrScW1o
NOP：http://markdown.4ye.me/qk1BET4J
薄荷糯米葱：http://markdown.4ye.me/ulxcoBmm
国美在线：http://markdown.4ye.me/r9Nq88R0
优集品：http://markdown.4ye.me/qpzmysKR
丽芙家居：http://markdown.4ye.me/HZA1hrIy
无印良品（中国）：http://markdown.4ye.me/hREmA1RY
YOHO!有货：http://markdown.4ye.me/r25NsdRV
新蛋中国：http://markdown.4ye.me/rEtHAkVb
欧舒丹中国：http://markdown.4ye.me/EaYwqyoI
凡夫：http://markdown.4ye.me/DjHDln4B
兰蔻（中国）：http://markdown.4ye.me/BXdMdSDM
KnewOne：http://markdown.4ye.me/se6Q3xiC
理肤泉：http://markdown.4ye.me/ftK8jAFA
良仓：http://markdown.4ye.me/yhsMxRN8
唯品会：http://markdown.4ye.me/WUY5QNGR

**Comment by fushang318** [comment]
infocard-services


写一个 rails 工程，用来解析收集 infocard 

# infocard 存储模型
```
infocard
  url
  hostname
  homepage
  image_url
  title
  desc
  price
  location
```



# 解析实现的使用方式如下

```
url = "http://detail.tmall.com/item.htm?id=15593325475&spm=a1z0k.7385961.1997985097.d4918997.lTDqPh&_u=rkkbfj13db&mt="

InfocardItem
 infocard_item = InfocardParser.parse(url)

# 网站名称
infocard_item.hostname

# 网站首页地址
infocard_item.homepage

# 图片
infocard_item.image_url

# 商品名称
infocard_item.title

# 商品描述
infocard_item.desc

# 定价
infocard_item.price

# 地理位置
infocard_item.location

```


下面以实现天猫的商品页解析类举例
```
url = "http://detail.tmall.com/item.htm?id=15593325475&spm=a1z0k.7385961.1997985097.d4918997.lTDqPh&_u=rkkbfj13db&mt="
u = URI.parse(url)

# 实现这个类方法
TmallInfocardParser.can_parse?(u.host)

# 实现这个类方法
infocard_item = TmallInfocardParser.parse(url)

# 实现以下几个解析信息方法
tmall_infocard_parser.get_hostname

tmall_infocard_parser.get_homepage

tmall_infocard_parser.get_image_url

tmall_infocard_parser.get_title

tmall_infocard_parser.get_desc

tmall_infocard_parser.get_price

tmall_infocard_parser.get_location
```

所有解析类都要实现 TmallInfocardParser 实现的这些方法


# 大概的一些实现代码
```
class InfocardParserFactory
  def self.parse(url)
    u = URI.parse(url)
    case true
    when TmallInfocardParser.can_parse?(u.host)
      return TmallInfocardParser.parse(url)
    when ....
      ...
    when ...
      ...
    end
  end
end

# 解析类里可以被所有解析类公用的代码，抽取到这个 module 
module InfocardParserMethods
  ........
end

class TmallInfocardParser
  inlcude InfocardParserMethods

  def self.parse(url)
    parser = self.new(url)
    item = InfocardItem.new
    item.hostname = parser.get_hostname
    ...........
    return item
  end

  # 实现其他方法
  ............

end

```

工作量最大的事情就是，实现各个解析类的 get_hostname get_homepage 这些方法

**Comment by chilliza** [comment]
通过与宋亮的讨论，商品描述字段可以不用采集。因为大多数情况下商品描述要不就没有，要不就内容特别多，infocard展示空间有限无法容纳。

**Comment by chilliza** [comment]
Amazon: http://markdown.4ye.me/ki2wsCb5 
Fab: http://markdown.4ye.me/R16G5TOK
ebay：http://markdown.4ye.me/JaPk6BFD
大众点评：http://markdown.4ye.me/j2Oi9SJu
yelp：http://markdown.4ye.me/FFXUhy7T
豆瓣阅读：http://markdown.4ye.me/oJTtqI27
豆瓣读书：http://markdown.4ye.me/pLVEXcqQ
多看阅读：http://markdown.4ye.me/ZisezjfX
豆瓣电影：http://markdown.4ye.me/IS0XuIU0
时光网：http://markdown.4ye.me/UfsKAK9l/1
IMDb：http://markdown.4ye.me/zEQpwdb2/1

**Comment by chilliza** [comment]
安卓市场：http://markdown.4ye.me/Pd7XyOXR
安智市场：http://markdown.4ye.me/PdvGHJJl
应用汇：http://markdown.4ye.me/Gg7tXH8a
豌豆荚：http://markdown.4ye.me/RpFBYjsI
机锋市场：http://markdown.4ye.me/ek8OrGkq
应用宝：http://markdown.4ye.me/IFWsnVr0
App Store（中国）：http://markdown.4ye.me/CGPT4gZM
iTunes Store - 播客（中国）:http://markdown.4ye.me/vCVWLVuJ
iTunes Store - 图书（中国）:http://markdown.4ye.me/bj8ypybt
豆瓣移动应用：http://markdown.4ye.me/nTMTIgDS
