### ISSUE TITLE
简单投票场景的改进

### ISSUE THREAD

**Issue by ben7th** [mindpin/TouchIdea#2]
https://github.com/mindpin/TouchIdea/issues/1
之前的这个任务已经提交到
https://github.com/arlyxiao/touch-vote-demo

现在需要对它进行一些改进：
1. 对于页面上显示几个条目，需要比较简化的配置方法
2. 把所有的条目信息改成图书，图书资料可以从豆瓣上找。
   把条目名称改成图书标题，把图书封面url和作者信息，组织成 JSON 然后存在 data 字段里
   贴图的话可以用 http://img.4ye.me/zmkm
3. 每次显示三本书的封面和标题，让人来点选
4. 当选择失败时，不alert，而是显示一个重来按钮。

**Comment by ben7th** [comment]
后续的考虑：（**肖少富可以先不管这一楼写的**）

从新浪微博收集一些名人的头像，微博数，粉丝数信息，整理成yaml，然后结合上面的场景做成小游戏。

**Comment by arlyxiao** [comment]
可以访问    https://touch-vote-demo.herokuapp.com/

**Comment by ben7th** [comment]
尚未集成，参考这里：
https://github.com/mindpin/TouchIdea/issues/1

先关闭了
