### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by destinyd** [mindpin/TouchIdea#29]
目前有四种触发通知的时机：

2.1 我参加的议题增加了选项
2.2 我创建的选项被人投票了
2.3 我创建的议题增加了选项
2.4 我创建的议题中有任意选项被人投票了

至于通知里写什么，宋亮考虑。

这些东西打算写在controller里。
至于通知模型使用原来的 Message，模型字段没有改变，考虑添加类函数，处理不同通知。

**Comment by destinyd** [comment]
## Message方法：

### 2.1 我参加的议题增加了选项

``` ruby
  def self.notify_voted_vote_has_new_select(vote_item)
  end
```

### 2.2 我创建的选项被人投票了

``` ruby
  def self.notify_vote_item_owner_be_selected(vote_item)
  end
```

### 2.3 我创建的议题增加了选项

``` ruby
  def self.notify_vote_has_new_select(vote_item)
  end
```

### 2.4 我创建的议题中有任意选项被人投票了

``` ruby
  def self.notify_vote_item_be_selected(vote_item)
  end
```

在需要提醒的点放入方法即会对对应用户进行提醒。

暂为这样，到时候看还能怎样优化。

**Comment by ben7th** [comment]
建议把创建 message 记录的触发放在模型层里，原因如下：
1. 可能后续版本会有不同的控制器（比如 ApiController ）会调用同样的模型方法；所以把回调放在模型层比较好
2. 用户数如果更多之后，可能消息通知会改用 sidekiq 等消息队列去创建 message 记录以提升性能。所以把这个逻辑放在模型层较好。

**Comment by ben7th** [comment]
### 2015 年 4 月 10 日，UI 初稿已提交，可以进行逻辑层面集成

在线观看地址：
http://www.mindpin.com/ui-design/pinidea/dist/html/notification-0-list.html

---

![](http://img.teamkn.com/i/ll8qD6zv.png)

集成注意事项：
- 上图中的前四个通知对应四种不同的通知类型，区别只是灰色文字不同
- 通知分为已读和未读，在 UI 上的区别就是背景色和文字颜色的区别。已读的背景更灰。所有刚创建出来的通知记录都是未读。只要用户点开通知页面，在这个页面上显示过一次的通知，就是已读。
- 所有通知按时间倒序排列，用户可以一直往下滚动查看所有更早的通知
- 一个需要注意的逻辑细节：如果用户的一个议题先后被四个不同的人增加了议题，那么应该只显示一条通知。也就是说，针对同一条议题发生的重复事件，只显示一条通知，具体如下：
  - 一个议题被反复增加投票，在通知未读之前，始终只显示一条通知。如果一个议题新增了 3 个投票，用户未点进该界面的情况下，又增加了 3 个投票，则直到用户查看通知为止，投票数只在这条未读的通知上累加，也就是 6 个投票；直到通知已读后，又增加了新的投票，则又创建出一条新的通知；
  - 一个议题被反复增加选项，在通知未读之前，始终只显示一条通知。如果一个议题新增了 3 个选项，用户未点进该界面的情况下，又增加了 3 个选项，则直到用户查看通知为止，选项数只在这条未读的通知上累加，也就是 6 个选项；直到通知已读后，又增加了新的选项，则又创建出一条新的通知；
  - 也就是说，逻辑流程是：
    1. 如果符合通知创建条件，则触发通知创建；
    2. 如果存在被通知的用户，针对该议题的同类型的未读通知，则累加计数；
    3. 如果不存在被通知的用户，针对该议题的同类型的未读通知，则创建新通知记录

**Comment by destinyd** [comment]
# Message模型

字段名

``` ruby
field :read_at, type: Time # 阅读时间
# 提醒类型 in %i[voted_vote_has_new_select own_vote_item_be_selected vote_has_new_select vote_item_be_selected]
field :style,    type: Symbol 
field :total,    type: Integer, default: 1 # 数目记录
```

方法

``` ruby
def read! # 标记为已读
end

def read? # 返回是否已读
end
```

类方法

``` ruby
  def self.notify to_user, vote, style # 创建对于style的提醒
  end

  def self.notify_voted_vote_has_new_select vote_item, from_user #2.1 我参加的议题增加了选项
  end

  def self.notify_vote_item_owner_be_selected vote_item, from_user #2.2 我创建的选项被人投票了
  end

  def self.notify_vote_has_new_select vote_item, from_user #2.3 我创建的议题增加了选项
  end

  def self.notify_vote_item_be_selected vote_item, from_user #2.4 我创建的议题中有任意选项被人投票了
  end
```

**Comment by destinyd** [comment]
4个事件触发已经集成到模型层内

**Comment by destinyd** [comment]
提醒规则进一步细化，防止过多重复的提醒：
1. 我参加的（别人创建的）议题增加了（别人创建的）选项
2. 我（在别人的议题中）（自己）创建的选项被（别人）投票了
3. 我（自己）创建的议题增加了（别人创建的）选项
4. 我（自己）创建的议题中有任意（不管是谁创建的）选项被（别人）投票了

**Comment by ben7th** [comment]
已集成到 0.2
