### ISSUE TITLE
后台管理功能的详细设计

### ISSUE THREAD

**Issue by fushang318** [mindpin/TouchIdea#33]
# 如何访问后台

电脑浏览器访问 pinidea.4ye.me/zmkm 页面
![](http://img.teamkn.com/i/cHrU8pcr.png)

输入管理用户名和管理员密码登陆进入后台首页
# 后台首页

![](http://img.teamkn.com/i/Pcidj9AR.png)

这个页面中有
1 搜索框（可以搜索 infocard）
2 infocard 的列表（显示系统中所有的infocard，包括网页分享议题用的 infocard 和点评议题用的 infocard）
3 infocard 的创建按钮（点击跳转到 infocard 新建表单页面,可以创建 点评议题用的 infocard）
4 点击列表中的 infocard，进入 infocard 详情页
# infocard 详情页

![](http://img.teamkn.com/i/ZyDEeoas.png)

这个页面中有
1 infocard 详情
2 编辑按钮（点击进入编辑页面）
3 删除按钮（删除该 infocard）
# infocard 搜索结果页面

![](http://img.teamkn.com/i/jAtZvvD9.png)

这个页面中有
1 infocard 搜索结果列表（点击进入 infocard 详情页面）

**Comment by ben7th** [comment]
已集成到 0.2
