### ISSUE TITLE
为多人意见汇总的基础组件增加修改功能

### ISSUE THREAD

**Issue by pimgeek** [mindpin/TouchIdea#4]
（注：这个 issue 是事后补充的 feature 划分说明）

目前，多人意见汇总的基础组件 #3 只允许创建议题后接受意见提交，某个议题一旦创建完毕，就不能修改了。

现在需要现有的意见汇总基础组件增加修改功能。

具体地说，在现有组件的【议事主题详情页面】，要增加一个【发起人修改议题】的按钮。如下图所示：

议题详情页面
![](http://img.teamkn.com/i/O7H81bXL.png)

用户点按此按钮时，就会打开议题编辑页面，如下图所示：

![](http://img.teamkn.com/i/QZKdee0G.png)

提交议题修改之后，将返回到议题列表页面，如下图所示：

![](http://img.teamkn.com/i/Vb2pzAZz.png)

**Comment by destinyd** [comment]
ac81968
e1dbe6f
54b4436
1bc8295
3b37308
