### ISSUE TITLE
为多人意见汇总的基础组件增加微博用户登录功能

### ISSUE THREAD

**Issue by pimgeek** [mindpin/TouchIdea#5]
（注：这个 issue 是事后补充的 feature 划分说明）

为了便于更多人试用 Touch Idea 产品，现需要引入新浪微博的用户登录功能。其大概运作流程如下图所示：

1 访问 Touch Idea 首页。

![](http://img.teamkn.com/i/fw0scqt3.png)

2 点击微博登录按钮之后：

依情况不同，最多需要经历两个先需步骤：若当前用户尚未登录新浪微博，则需要输入用户名密码登录一次，授权 Touch Idea 应用访问用户的微博账号，即可出现当前用户的议题列表页面：

![](http://img.teamkn.com/i/JrUq4fDO.png)

**Comment by ben7th** [comment]
0.2 已经包含此特性。
