### ISSUE TITLE
需要一个组件：获取当前已登录微博账号的所有互粉好友

### ISSUE THREAD

**Issue by pimgeek** [mindpin/TouchIdea#7]
现在需要在新浪微博用户系统 #5 的基础上，实现一个获取当前已登录微博账号的所有互粉好友列表的组件。

其主要功能描述如下：

当用户通过某个新浪微博账号登录到 Touch Idea 中之后，利用这一组件可以获得此账号的所有互粉好友列表。

**Comment by ben7th** [comment]
目前暂时用不到此组件。
