### ISSUE TITLE
基于新浪微博用户系统实现一种站内提醒组件

### ISSUE THREAD

**Issue by pimgeek** [mindpin/TouchIdea#8]
为了提升多人议事的交互体验，现需要在多人意见汇总组件 #3 ，支持新浪微博用户系统 #5，可获取当前已登录账号的所有互粉好友 #7 的基础上，实现一种站内提醒组件。

站内提醒组件的主要功能描述如下：

1 发起新议题时，在原有议题创建和修改界面的基础上，加入互粉好友列表。
2 每个互粉好友都对应有一个复选框，如果某些好友对应的复选框被选中，那么提交议题之后，这些好友下次登录 Touch Idea 时，将会收到站内提醒。

![](http://img.teamkn.com/i/aFWLNTec.png)

3 收到站内提醒时的界面，如下图所示：

![](http://img.teamkn.com/i/QnFALpkO.png)

**Comment by ben7th** [comment]
目前暂时用不到此组件
