### ISSUE TITLE
实现一个自动发微博 @ 指定互粉好友的组件

### ISSUE THREAD

**Issue by pimgeek** [mindpin/TouchIdea#9]
现在需要在站内提醒组件 #8 的基础上，实现一个自动发微博 @ 指定互粉好友的组件。

具体功能描述如下：

1 用户发起新议题时，每个互粉好友都对应有一个复选框，如果某些好友对应的复选框被选中，那么提交议题之后，发起者对应的新浪微博账号将会自动发送一条微博。

![](http://img.teamkn.com/i/aFWLNTec.png)

2 发起者发送新浪微博 @ 指定互粉好友的实际效果，如下图所示：

![](http://img.teamkn.com/i/L4vPg0kX.png)

**Comment by ben7th** [comment]
目前暂时用不到此组件
